from abc import ABC, abstractmethod
from itertools import product
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

from cutpointpy.utils import auc as area_under_curve,\
     check_same_length, cm, cm_performance_metrics

class CutpointCalculator():
    """
    Performs optimal cut-point calculation and bootstrapping.
    """
    
    def __init__(self, target='youdenj', polarity=True, 
                 interpolation=None, num_points=100):
        """
        Parameters
        ----------
        target : str
            The target function to maximise or minimise. 
            Possible values:
                'youdenj' -> see `Youdenj` class documentation.
                'eucdist' -> see `Eucdist` class documentation.
        polarity : bool
            The direction of the inequality. If True (False) the 
            datapoints with feature value greater (less) than or equal 
            to the threshold are flagged as positive and the other ones 
            as negative.
        interpolation : str [optional]
            Interpolation method for generating the set of thresholds
            to test. Possible values:
                None     -> No interpolation is used. The optimal 
                            cut-point is chosen among the feature 
                            values.
                'linear' -> Thresholds are generated by linear
                            interpolation between the min and max value 
                            of `features`.
        num_points : unsigned int [optional]
            Number of thresholds generated. Has no effect if `interpolation`
            is None.
        """
        
        match target:
            case 'eucdist':
                self.optimal_cpcalculator = Eucdist()
            case 'youdenj':
                self.optimal_cpcalculator = Youdenj()
            case _:
                raise ValueError(f'Target `{target}` not recognised.')
                
        self.above = polarity
        self.interpolation = interpolation
        self.num_points = num_points
            
    def find(self, features, labels):
        """
        Determine the optimal cut-point value of a predictor variable 
        (feature) for a binary classification task.
            
        Parameters
        ----------
        features : array-like of numeric (n_samples)
            Value of the predictor variable for each datapoint. 
            It is converted to an ndarray of float internally.
        labels : array-like of numeric (n_samples)
            Class label of each datapoint, where 0 indicates negative 
            and any other value positive. It is converted to an ndarray of 
            bool internally.
   
        Returns
        -------
        cutpoint : float
            The optimal cut-point value.
        cutpoint_idx : int
            The index corresponding to the optimal cut-point value
            among the thresholds tested.
        thresholds : ndarray of numeric (N,1)
            The thresholds tested. N = len(features) if 
            `self.interpolation` is None, otherwise N = num_points.
        acc : ndarray of numeric (N,1)
            Accuracy as a function of the thresholds.
        se : ndarray of numeric (N,1)
            Sensitivity as a function of the thresholds.
        sp : ndarray of numeric (N,1)
            Specificity as a function of the thresholds.
        auc : float
            The area under the receiver-operating characteristic (ROC) 
            curve.
         
        References
        ----------
        1. Hassanzad and Haijan-Tilaki (2024) 
           doi:10.1186/s12874-024-02198-2 
        """
                
        if not check_same_length(features, labels):
            raise ValueError('There should be as many features as '
                             'labels')
            
        #Labels and features: cast and reshape
        features, labels = self._cast_and_reshape(features, labels)
                
        #Sort datapoints in ascending order by feature value
        sorted_idxs = np.argsort(features, axis=0)
        features, labels =\
            [np.take_along_axis(x, sorted_idxs, axis=0) for x in 
             [features, labels]]
                
        #Define the set of thresholds to test
        if self.interpolation:
                    
            lingrid = np.linspace(start=np.min(features[:, 0]),
                                  stop=np.max(features[:, 0]),
                                  num=self.num_points)
                    
            match self.interpolation:
                case 'linear':
                    thresholds = np.interp(
                        x=lingrid, xp=features[:, 0], fp=features[:, 0])
                case _:
                    raise ValueError(f'Interpolation "{interpolation}" '
                                     f'not recognised')
            
            thresholds.shape = (thresholds.size, 1)
        else:
            thresholds = features
                    
        acc, se, sp, cutpoint, cutpoint_idx, auc =\
            self._test_cutoff_values(
                features=features, 
                labels=labels, 
                thresholds=thresholds,
            )
                            
        return cutpoint, cutpoint_idx, thresholds, acc, se, sp, auc
    
    def bootstrap(self, features, labels, method='sss', train_ratio=0.7, 
                  num_reps=30, random_state=0):
        """
        Compute/validate optimal cut-point through bootstrapping.
        
        Parameters
        ----------
        features : array-like of numeric (n_samples)
            Value of the predictor variable for each datapoint. It is 
            converted to ndarray of float internally.
        labels : array-like of numeric (n_samples)
            Class label of each datapoint, where 0 indicates negative 
            and any other value positive. It is converted to ndarray of 
            bool internally.
        method : str
            The strategy for generating the bootstratp repetitions-i.e.,
            the subdivisions of the original data into train (in-bag
            data) and test set (out-of-bag data).
            Possible values:
                `sss` -> Stratified shuffle split
        train_ratio : float [0.0, 1.0]
            The proportion of the original data used to generate the 
            train set at each repetition.
        num_reps : int
            Number of bootstrap repetitions (i.e., number of 
            subdivisions into train and test set).
        random_state : int
            Controls the randomness of the repetitions produced. Pass 
            an int for reproducible output across multiple function 
            calls, None for non-reproducible output.
            
        Returns
        -------
        cutpoints : ndarray of float (num_reps, 1)
            The optimal cut-point value for each repetition estimated 
            on the train set.
        cutpoints_idxs : ndarray of float (num_reps, 1)
            For each repetition the index of the optimal cut-point value
            correspoinding to the thresholds tested on the train set.
        thresholds : ndarray of float (num_reps, N)
            The values of the thresholds tested on the train set at each
            repetion. Element [i,j] of the matrix represents the j-th
            threshold value for repetition i. 
            N = floor(len(`features`) * `train_ratio`) if
            `self.interpolation` is None, otherwise N =
            `self.num_points`.
        accs : ndarray of float (num_reps, N)
            Accuracy on the train set for each repetition and threshold
            value tested.
        ses : ndarray of float (num_reps, N)
            Sensitivity on the train set for each repetition and
            threshold value tested.
        sps : ndarray of float (num_reps, N)
            Specificity on the train set for each repetition and
            threshold value tested.    
        aucs_train : ndarray of float (num_reps, 1)
            The area under the curve for each repetition estimated on 
            the train set.
        aucs_test : ndarray of float (num_reps, 1)
            The area under the curve for each repetition estimated on 
            the test set.
        performance_train : ndarray of float (num_reps, 3)
            For each repetition, in column-wise order, respectively 
            accuracy, sensitivity and specificity yielded by the optimal
            cut-point value when applied to the train set.
        performance_test : ndarray of float (num_reps, 3)
            For each repetition, in column-wise order, respectively
            accuracy, sensitivity and specificity yielded by the optimal
            cut-point value when applied to the test set.
        performance_whole : ndarray of float (num_reps, 3)
            For each repetition, in column-wise order, respectively
            accuracy, sensitivity and specificity yielded by the optimal
            cut-point value when applied to the whole dataset.
        """
        
        features, labels = self._cast_and_reshape(features, labels)
        
        #===============================================================
        #================ Initialise the output ========================
        #===============================================================
        cutpoints, cutpoints_idxs, aucs_train, aucs_test =\
            [np.zeros(shape=(num_reps,1), dtype=float) for _ in range(4)]
        performance_train, performance_test, performance_whole =\
            [np.zeros(shape=(num_reps,3), dtype=float) for _ in range(3)]
        
        if self.interpolation:
            num_thresholds = self.num_points
        else:
            num_thresholds = np.floor(
                len(features) * train_ratio, 
                dtype=int, casting='unsafe'
            )
            
        thresholds, accs, ses, sps = \
            [np.zeros(shape=(num_reps, num_thresholds), dtype=float) 
             for _ in range(4)]
        #===============================================================
        #===============================================================
        #===============================================================
        
        
        match method:
            case 'sss':
                splitter = StratifiedShuffleSplit(
                    n_splits=num_reps, 
                    train_size=train_ratio, 
                    random_state=random_state
                )
            case _:
                raise ValueError(f'Unrecognised method `{method}`.')
            
        for split_idx, (train_idxs, test_idxs) in enumerate(
            splitter.split(X=features, y=labels)):
            
            [train_features, test_features, train_labels, test_labels]=\
                [container[idxs] for container, idxs in 
                 product((features, labels), (train_idxs, test_idxs))]
            
            #===========================================================
            #==== Return values computed on the train (in bag) data ====
            #===========================================================
            cutpoint, cutpoint_idx, thresholds_, acc, se, sp, auc =\
                self.find(train_features, train_labels)        
            
            for out_, in_ in zip((cutpoints, cutpoints_idxs), 
                                 (cutpoint, cutpoint_idx)):
                out_[split_idx,:] = in_            
            
            for out_, in_ in zip((thresholds, accs, ses, sps), 
                                 (thresholds_, acc, se, sp)):
                out_[split_idx,:] = in_.flat
            
            for i, in_ in enumerate([acc, se, sp]):
                performance_train[split_idx, i] = in_[cutpoint_idx,0]
            
            aucs_train[split_idx,0] = auc
            #===========================================================
            #===========================================================
            #===========================================================
            
            #Compute auc on the test set
            _, _, _, _, _, _, aucs_test[split_idx,0] =\
                self.find(test_features, test_labels)            
            
            #Compute performance parameters on the test set using the 
            #cut-point value estimated on the train set
            acc, se, sp, _, _, _ = self._test_cutoff_values(
                features=test_features, 
                labels=test_labels, 
                thresholds = np.array(cutpoint, ndmin=2), 
            )
            for i, in_ in enumerate([acc, se, sp]):
                performance_test[split_idx, i] = in_[0,0]            
            
            #Compute performance parameters on the whole dataset using 
            #the cut-point value estimated on the train set
            acc, se, sp, _, _, _ = self._test_cutoff_values(
                features=features, 
                labels=labels, 
                thresholds = np.array(cutpoint, ndmin=2), 
            )
            for i, in_ in enumerate([acc, se, sp]):
                performance_whole[split_idx, i] = in_[0,0]      
            
        return cutpoints, cutpoints_idxs, thresholds, accs, ses, sps,\
               aucs_train, aucs_test, performance_train,\
               performance_test, performance_whole        

    def _test_cutoff_values(self, features, labels, thresholds):
        """
        Classification performance of a set of cut-off values
        (thresholds) when applied to a predictor variable (feature) for
        a binary classification task.
    
        Parameters
        ----------
        features : ndarray of float (n_features, 1)
            Value of the predictor variable for each datapoint. 
        labels : ndarray of bool (n_features, 1)
            Class label of each datapoint, where True indicates the
            positive class.
        thresholds : ndarray of float (n_thresholds, 1)
            The cut-off values to be tested, sorted in ascending order.
        
        Returns
        -------
        acc, se, sp : ndarrays of float, each of shape (n_thresholds, 1)
            Accuracy, sensitivity and pecificity as a function of the 
            cut-off value.
        cutpoint : float    
            The optimal cut-off value.
        cutpoint_idx : int [0, (n_thresholds - 1)]
            Index of the optimal cut-off value.
        auc : float
            The area under the curve.
        """
    
        #Reshape features and thresholds for vectorisation. 
        #Prepend 'r_' to indicate the reshaped versions
        r_features = np.tile(features.T, reps=(thresholds.size, 1))
        r_thresholds = np.tile(thresholds, reps=(1, features.size))

        #Predict labels as a function of threshold
        if self.above:
            predicted = (r_features >= r_thresholds)
        else:
            predicted = (r_features <= r_thresholds)
    
        #Compute sensitivity and specificity as a function of threshold
        confmat = cm(predicted=predicted,
                     target=np.tile(labels.T, reps=(thresholds.size, 1)))
        acc, se, sp = cm_performance_metrics(confmat)
    
        #Compute optimal cutpoint
        cutpoint, cutpoint_idx = self.optimal_cpcalculator.find(
            thresholds=thresholds, se=se, sp=sp
        )
    
        #Compute AUC
        auc = area_under_curve(se=se.T, sp=sp.T).flatten()[0]
    
        return acc, se, sp, cutpoint, cutpoint_idx, auc
    
    @staticmethod
    def _cast_and_reshape(features, labels):
        """
        Convert and reshape features and labels to ndarray.
        
        Parameters
        ----------
        features : array-like of numeric (n_samples)
            Value of the predictor variable for each datapoint. 
        labels : array-like of numeric (n_samples)
            Class label of each datapoint, where 0 indicates negative 
            and any other value positive.
            
        Returns
        -------
        features : ndarray of float (n_samples, 1)
            Cast and reshaped features.
        labels : ndarray of bool (n_samples, 1)
            Cast and reshaped labels.
        """
        
        check_same_length(features, labels)
         
        features = np.array(features, dtype=float, ndmin=2)
        labels = np.array(labels, dtype=bool, ndmin=2)
        
        for item in [features, labels]:
            item.shape = (features.size, 1)
        
        return features, labels
    
    
    
class OptimalCutpointCalculator(ABC):
    """
    Encapsulates the target function to maximise or minimise. 
    """
    
    @staticmethod
    @abstractmethod
    def find(thresholds, se, sp):
        """
        Determine the optimal cut-point given sensitivity and specificity as a
        function of the thresholds tested.
    
        Parameters
        ----------
        thresholds : ndarray of float (N,1)
            The set of thresholds to test, sorted from smallest to 
            largest.
        se : ndarray of float (N,1)
            Sensitivity as a function of the threshold.
        sp : ndarray of float (N,1)
            Specificity as a function of the threshold.
                         
        Returns
        -------
        cutpoint : numeric
            The optimal cut-point value.
        cutpoint_idx : int
            The index corresponding to optimal cut-point value.
        """
        pass
    
class Youdenj(OptimalCutpointCalculator):
    """
    Maximises Youden’s J - i.e.: Sensitivity + Specificity - 1.
    """
    
    @staticmethod
    def find(thresholds, se, sp):
        """
        Note
        ----
        If the maximum occurrs on multiple values of threshold the first
        (smallest) occurrence is returned.
        """
        target_values = se + sp - 1
        idx = np.argmax(target_values, axis=0).flatten()[0]
        return thresholds[idx, 0], idx
    
class Eucdist(OptimalCutpointCalculator):
    """
    Minimises the Euclidean distance between the (0,1) point and the ROC curve
    in the FPR (1 - sp) vs. TPR (se) space.
    """
    
    @staticmethod
    def find(thresholds, se, sp):
        """
        Note
        ----
        If the minimum occurrs on multiple values of threshold the last
        (largest) occurrence is returned.
        """        
        target_values = np.sqrt((1 - se)**2 + (1 - sp)**2)
        idx = np.argmin(target_values, axis=0).flatten()[-1]
        return thresholds[idx, 0], idx