import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

from cutpointpy.utils import auc as area_under_curve,\
     check_same_length, cm, cm_performance_metrics

def _compute_optimal_cutpoint(thresholds, se, sp, target):
    """
    Determine the optimal cut-point given sensitivity and specificity as a 
    function of the thresholds tested.
    
    Parameters
    ----------
    thresholds : ndarray of float (N,1)
        The set of thresholds to test, sorted from smallest to largest.
    se : ndarray of float (N,1)
        Sensitivity as a function of the threshold.
    sp : ndarray of float (N,1)
        Specificity as a function of the threshold.
    target : str
        The target function to maximise or minimise. Possible values:
            'youdenj' -> Maximum of Youden’s J (Sensitivity + Specificity 
                         - 1)
            'eucdist' -> Minimum of the Euclidean distance between the (0,1) 
                         point and the ROC curve in the FPR/TPR space.
                             
    Returns
    -------
    cutpoint : numeric
        The optimal cut-point value.
    cutpoint_idx : int
        The index corresponding to optimal cut-point value.
        
    Note
    ----
    If the maximum of `target` occurs on multiple values of `thresholds`, the
    the first (smallest) value of `thresholds` is returned as the 
    optimal `cutpoint` value. 
    """
    if not (thresholds.shape == se.shape == sp.shape):
        raise ValueError(f'All of `thresholds`, `se` and `sp` should '
                         f'have the same shape')

    match target:
        case 'youdenj':
            target_values = se + sp - 1
            idx = np.argmax(target_values)
        case 'eucdist':
            target_values = np.sqrt((1 - se)**2 + (1 - sp)**2)
            idx = np.argmin(target_values)
        case _:
            raise ValueError(
                f'Target `{target}` not recognised.')
        
    return thresholds[idx, 0], idx
        

def find_cutpoint(features, labels, above=True, target='youdenj', 
                  interpolation=None, num_points=100):
    """
    Determine the optimal cut-point value of a predictor variable (feature) 
    for a binary classification task.

    Parameters
    ----------
    features : iterable of numeric (n_samples)
        Value of the predictor variable for each datapoint. It is converted
        to ndarray of float internally.
    labels : iterable of numeric (n_samples)
        Class label of each datapoint, where 0 indicates negative and any
        other value positive. It is converted to ndarray of bool internally.
    above : bool
        The direction of the inequality. If True the datapoints with
        feature value above the threshold are flagged as positive,
        and those with value below the threshold as negative. If False
        the reverse happens.
    target : str
        The target function to maximise. See `_optimal_cutpoint()` for
        possible values.
    interpolation : str [optional]
        Interpolation method for generating the set of thresholds tested.
        Possible values:
            None     -> No interpolation is used. The optimal cut-point is
                        chosen among the feature values.
            'linear' -> Thresholds are generated by linear interpolation
                        between the min and max value of `features`.
        num_points : unsigned int [optional]
            Number of thresholds generated if `ìnterpolation` is not None.    

    Returns
    -------
    cutpoint : float
        The optimal cut-point value.
    cutpoint_idx : int
        The index corresponding to optimal cut-point value.
    thresholds : ndarray of numeric (N,1)
        The thresholds tested. N = len(features) if interpolation = None,
        otherwise N = num_points.
    acc : ndarray of numeric (N,1)
        Accuracy as a function of the thresholds.
    se : ndarray of numeric (N,1)
        Sensitivity as a function of the thresholds.
    sp : ndarray of numeric (N,1)
        Specificity as a function of the thresholds.
    auc : float
        The area under the receiver-operating characteristic (ROC) 
        curve.
    
    References :
        - Hassanzad and Haijan-Tilaki (2024) doi:10.1186/s12874-024-02198-2 
    """
    
    if not check_same_length(features, labels):
        raise ValueError('There should be as many features as labels')

    #Labels and features: convert and reshape
    labels = np.array(labels, dtype=bool, ndmin=2)
    features = np.array(features, dtype=float, ndmin=2)
    
    #Sort datapoints in ascending order by feature value
    sorted_idxs = np.argsort(features.flatten())
    features = features[:, sorted_idxs]
    labels = labels[:,sorted_idxs]
    
    #Define the set of thresholds to test as optimal cut-points
    if interpolation:
        
        lingrid = np.linspace(start=np.min(features[0, :]),
                              stop=np.max(features[0, :]),
                              num=num_points)
        
        match interpolation:
            case 'linear':
                thresholds = np.interp(
                    x=lingrid, xp=features[0, :], fp=features[0, :])
                thresholds = np.array(thresholds, ndmin=2)
            case _:
                raise ValueError(f'Interpolation "{interpolation}" not '
                                 f'recognised')
    else:
        thresholds = features
        
    acc, se, sp, cutpoint, cutpoint_idx, auc = _test_cutoff_values(
        features=features, 
        labels=labels, 
        thresholds=thresholds,
        above=above,
        target=target
    )
                
    return cutpoint, cutpoint_idx, thresholds.T, acc, se, sp, auc

def cutpoint_boot(features, labels, above=True, target='youdenj', method='sss', 
                  train_ratio=0.7, nruns=30, random_state=0, 
                  find_cutpoint_kw=None):
    """
    Compute/validate optimal cut-point trough bootstrapping.
    
    Parameters
    ----------
    features : iterable of numeric (n_samples)
        Value of the predictor variable for each datapoint. It is 
        converted to ndarray of float internally.
    labels : iterable of numeric (n_samples)
        Class label of each datapoint, where 0 indicates negative and 
        any other value positive. It is converted to ndarray of bool 
        internally.
    above : bool
        The direction of the inequality. If True the datapoints with
        feature value above the threshold are flagged as positive,
        and those with value below the threshold as negative. If False
        the reverse happens.
    target : str
        The target function to maximise. See `find_cutpoint()` for
        possible values.
    method : str
        The strategy for generating bootstratp repetitions - i.e.,
        subdivisions of the original data into train and test set.
        Possible values:
            `sss` -> Stratified shuffle split
    train_ratio : float [0.0, 1.0]
        The proportion of the original data used to estimate the cut-
        point value (train set)
    nruns : int
        Number of bootstrap repetitions (i.e., number of subdivisions
        into train and test set).
    random_state : int
        Controls the randomness of the repetitions produced. Pass an 
        int for reproducible output across multiple function calls, 
        None for non-reproducible output.
    find_cutpoint_kw : dict (optional)
        Keyword arguments to be passed to the `find_cutpoint` 
        function (see related documentation for details).
        
    Returns
    -------
    cutpoints : ndarray of float (nruns, 1)
        The optimal cut-point value for each bootstrap run estimated on the
        train set.
    aucs : ndarray of float (nruns, 1)
        The area under the curve for each bootstrap run estimated on the train 
        set.
    performance_train : ndarray of float (nruns, 3)
        In column-wise order, respectively accuracy, sensitivity and specificity 
        yielded by the optimal cut-point value when applied to the train set.
    performance_test : ndarray of float (nruns, 3)
        In column-wise order, respectively accuracy, sensitivity and specificity 
        yielded by the optimal cut-point value when applied to the test set.
    performance_whole : ndarray of float (nruns, 3)
        In column-wise order, respectively accuracy, sensitivity and specificity 
        yielded by the optimal cut-point value when applied to the whole 
        dataset.
    """
    check_same_length(features, labels)
    
    #Initialise output
    cutpoints, aucs = [np.zeros(shape=(nruns,1), dtype=float) for _ in range(2)]
    performance_train, performance_test, performance_whole =\
        [np.zeros(shape=(nruns,3), dtype=float) for _ in range(3)]
    
    match method:
        case 'sss':
            splitter = StratifiedShuffleSplit(
                n_splits=nruns, 
                train_size=train_ratio, 
                random_state=random_state
            )
        case _:
            raise ValueError(f'Unrecognised method `{method}`.')
        
    for split_idx, (train_idxs, test_idxs) in enumerate(
        splitter.split(X=features, y=labels)):
        
        train_features = features[train_idxs]
        train_labels = labels[train_idxs]
        test_features = features[test_idxs]
        test_labels = labels[test_idxs]
        
        #Compute cut-point value and performance parameters on the train set
        cutpoint, cutpoint_idx, _, acc, se, sp, auc =\
            find_cutpoint(
                train_features, train_labels, **find_cutpoint_kw
            )        
        
        cutpoints[split_idx,0] = cutpoint
        performance_train[split_idx,0:3] = acc[cutpoint_idx,0],\
            se[cutpoint_idx,0], sp[cutpoint_idx,0]
        aucs[split_idx,0] = auc
        
        #Compute performance parameters on the test set using the cut-point
        #value determined on the train set
        acc, se, sp, _, _, _ = _test_cutoff_values(
            features=test_features, 
            labels=test_labels, 
            thresholds = np.array(cutpoint, ndmin=2), 
            above=above, 
            target=target
        )
        performance_test[split_idx,0:3] = acc[0,0], se[0,0], sp[0,0]
        
        #Compute performance parameters on the whole dataset using the cut-point
        #value determined on the train set
        acc, se, sp, _, _, _ = _test_cutoff_values(
            features=features, 
            labels=labels, 
            thresholds = np.array(cutpoint, ndmin=2), 
            above=above, 
            target=target
        )
        performance_whole[split_idx,0:3] = acc[0,0], se[0,0], sp[0,0]        
        
    return cutpoints, aucs, performance_train, performance_test,\
           performance_whole

def _test_cutoff_values(features, labels, thresholds, above, target):
    """
    Test the classification performance of a set of cut-off values
    for a binary classification task.
    
    Parameters
    ----------
    features : ndarray of float (n_features, 1)
        Value of the predictor variable for each datapoint. 
    labels : ndarray of bool (n_features, 1)
        Class label of each datapoint, where True indicates the
        positive class.
    thresholds : ndarray of float (n_thresholds, 1)
        The cut-off values to be tested, sorted in ascending order.
    above : bool
        The direction of the inequality. If True the datapoints with
        feature value above the threshold are flagged as positive,
        and those with value below the threshold as negative. If False
        the reverse happens.
    target : str
        The target function to maximise or minimise. See 
        `optimal_cutpoint()` fro possible values.
        
    Returns
    -------
    acc, se, sp : ndarrays of float, each of shape (n_thresholds, 1)
        Accuracy, sensitivity and pecificity as a function of the 
        cut-off value.
    cutpoint : float    
        The optimal cut-off value.
    cutpoint_idx : int [0, (n_thresholds - 1)]
        Index of the optimal cut-off value.
    auc : float
        The area under the curve.
    """
    
    #Reshape features and thresholds for vectorisation. Prepend 'r_' to
    #indicate the reshaped versions
    r_features = np.tile(features, reps=(thresholds.size, 1))
    r_thresholds = np.tile(thresholds.T, reps=(1, features.size))

    #Predicted labels as a function of threshold
    if above:
        predicted = (r_features >= r_thresholds)
    else:
        predicted = (r_features <= r_thresholds)
    
    #Sensitivity and specificity as a function of threshold
    confmat = cm(predicted=predicted,
                 target=np.tile(labels, reps=(thresholds.size, 1)))
    acc, se, sp = cm_performance_metrics(confmat)
    
    #Optimal cutpoint
    thresholds = thresholds.T
    cutpoint, cutpoint_idx = _compute_optimal_cutpoint(
        thresholds=thresholds, se=se, sp=sp, target=target)
    
    #AUC
    auc = area_under_curve(se=se, sp=sp).flatten()[0]
    
    return acc, se, sp, cutpoint, cutpoint_idx, auc