import numpy as np
import warnings

from cutpointpy.utils import check_same_length, cm, cm_performance_metrics

def optimal_cutpoint(thresholds, se, sp, target):
    """
    Determine he optimal cut-point given sensitivity and specificity as a 
    function of the thresholds tested.
    
    Parameters
    ----------
    thresholds : ndarray of float (N,1)
        The set of thresholds to test, sorted from smallest to largest.
    se : ndarray of float (N,1)
        Sensitivity as a function of the threshold.
    sp : ndarray of float (N,1)
        Specificity as a function of the threshold.
    target : str
        The target function to maximise or minimise. Possible values:
            'youdenj' -> Maximum of Youden’s J (Sensitivity + Specificity 
                         - 1)
            'eucdist' -> Minimum of the Euclidean distance between the (0,1) 
                         point and the ROC curve in the FPR/TPR space.
                             
    Returns
    -------
    cutpoint : numeric
        The optimal cut-point value.
    cutpoint_idx : int
        The index corresponding to optimal cut-point value.
        
    Note
    ----
    If the maximum of `target` occurs on multiple values of `thresholds`, the
    the first (smallest) value of `thresholds` is returned as the 
    optimal `cutpoint` value. 
    """
    if not (thresholds.shape == se.shape == sp.shape):
        raise ValueError(f'All of `thresholds`, `se` and `sp` should '
                         f'have the same shape')

    match target:
        case 'youdenj':
            target_values = se + sp - 1
            idx = np.argmax(target_values)
        case 'eucdist':
            target_values = np.sqrt((1 - se)**2 + (1 - sp)**2)
            idx = np.argmin(target_values)
        case _:
            raise ValueError(
                f'Target `{target}` not recognised.')
        


    return thresholds[idx, 0], idx
        

def cutpoint(features, labels, target='youdenj', above=True,
             interpolation=None, num_points=100):
    """
    Determine the optimal cut-point value of a predictor variable (feature) 
    for a binary classification task.

    Parameters
    ----------
    features : iterable of numeric (n_samples)
        Value of the predictor variable for each datapoint. It is converted
        to ndarray of float internally.
    labels : iterable of numeric (n_samples)
        Class label of each datapoint, where 0 indicates negative and any
        other value positive. It is converted to ndarray of bool internally.
    target : str
        The target function to maximise. See `_optimal_cutpoint()` for
        possible values.
    above : bool
        The direction of the inequality. If True the datapoints with
        feature value above the threshold are flagged as positive,
        and those with value below the threshold as negative. If False
        the reverse happens.
    interpolation : str [optional]
        Interpolation method for generating the set of thresholds tested.
        Possible values:
            None     -> No interpolation is used. The optimal cut-point is
                        chosen among the feature values.
            'linear' -> Thresholds are generated by linear interpolation
                        between the min and max value of `features`.
        num_points : unsigned int [optional]
            Number of thresholds generated if `ìnterpolation` is not None.    

    Returns
    -------
    cutpoint : numeric
        The optimal cut-point value.
    cutpoint_idx : int
        The index corresponding to optimal cut-point value.
    thresholds : ndarray of numeric (N,1)
        The thresholds tested. N = len(features) if interpolation = None,
        otherwise N = num_points.
    se : ndarray of numeric (N,1)
        Sensitivity as a function of the thresholds.
    sp : ndarray of numeric (N,1)
        Specificity as a function of the thresholds.
    
    References :
        - Hassanzad and Haijan-Tilaki (2024) doi:10.1186/s12874-024-02198-2 
    """
    
    if not check_same_length(features, labels):
        raise ValueError('There should be as many features as labels')

    #Labels and features: convert and reshape
    labels = np.array(labels, dtype=bool, ndmin=2)
    features = np.array(features, dtype=float, ndmin=2)
    
    #Sort datapoints in ascending order by feature value
    sorted_idxs = np.argsort(features.flatten())
    features = features[:, sorted_idxs]
    labels = labels[:,sorted_idxs]
    
    #Define the set of thresholds to test as optimal cut-points
    if interpolation:
        
        lingrid = np.linspace(start=np.min(features[0, :]),
                              stop=np.max(features[0, :]),
                              num=num_points)
        
        match interpolation:
            case 'linear':
                thresholds = np.interp(
                    x=lingrid, xp=features[0, :], fp=features[0, :])
            case _:
                raise ValueError(f'Interpolation "{interpolation}" not '
                                 f'recognised')
    else:
        thresholds = features
        
    #Reshape features and thresholds for vectorisation. Prepend 'r_' to
    #indicate the reshaped versions
    r_features = np.tile(features, reps=(thresholds.size, 1))
    r_thresholds = np.tile(thresholds.T, reps=(1, features.size))

    #Predicted labels as a function of threshold
    if above:
        predicted = (r_features >= r_thresholds)
    else:
        predicted = (r_features <= r_thresholds)
    
    #Sensitivity and specificity as a function of threshold
    confmat = cm(predicted=predicted,
                 target=np.tile(labels, reps=(thresholds.size, 1)))
    _, se, sp = cm_performance_metrics(confmat)
    
    #Optimal cutpoint
    thresholds = thresholds.T
    cutpoint, cutpoint_idx = optimal_cutpoint(
        thresholds=thresholds, se=se, sp=sp, target=target)
        
    return cutpoint, cutpoint_idx, thresholds, se, sp

